// <auto-generated />
using System;
using MediaReviewHubWeb.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaReviewHub.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241003185320_SeedReviewsToDb")]
    partial class SeedReviewsToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaReviewHub.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateReviewed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReviewID");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewID = 1,
                            Category = "Movies",
                            DateReviewed = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            ReviewText = "A mind-bending thriller with stunning visuals.",
                            Title = "Inception"
                        },
                        new
                        {
                            ReviewID = 2,
                            Category = "Books",
                            DateReviewed = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            ReviewText = "A classic novel about the American dream.",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            ReviewID = 3,
                            Category = "Movies",
                            DateReviewed = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            ReviewText = "A visually stunning space exploration journey.",
                            Title = "Interstellar"
                        },
                        new
                        {
                            ReviewID = 4,
                            Category = "Books",
                            DateReviewed = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            ReviewText = "A magical fable about following your dreams.",
                            Title = "The Alchemist"
                        },
                        new
                        {
                            ReviewID = 5,
                            Category = "Music",
                            DateReviewed = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            ReviewText = "A legendary song by Queen.",
                            Title = "Bohemian Rhapsody"
                        },
                        new
                        {
                            ReviewID = 6,
                            Category = "Movies",
                            DateReviewed = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            ReviewText = "An epic tale of a mafia family.",
                            Title = "The Godfather"
                        },
                        new
                        {
                            ReviewID = 7,
                            Category = "Books",
                            DateReviewed = new DateTime(2024, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            ReviewText = "A novel about racial injustice in the American South.",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            ReviewID = 8,
                            Category = "Games",
                            DateReviewed = new DateTime(2024, 10, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            ReviewText = "An epic adventure game with stunning combat.",
                            Title = "God of War"
                        },
                        new
                        {
                            ReviewID = 9,
                            Category = "Games",
                            DateReviewed = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            ReviewText = "An open-world Western adventure.",
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            ReviewID = 10,
                            Category = "Music",
                            DateReviewed = new DateTime(2024, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            ReviewText = "A legendary album by The Beatles.",
                            Title = "The Beatles - Abbey Road"
                        },
                        new
                        {
                            ReviewID = 11,
                            Category = "Movies",
                            DateReviewed = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 5,
                            ReviewText = "A sci-fi movie about reality and human existence.",
                            Title = "The Matrix"
                        },
                        new
                        {
                            ReviewID = 12,
                            Category = "Books",
                            DateReviewed = new DateTime(2024, 10, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Rating = 4,
                            ReviewText = "A dystopian novel about surveillance and totalitarianism.",
                            Title = "1984"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
